### PR TITLE
Read screens from Tailwind config

### LINKED ISSUE #1: Read breakpoints from tailwind.config.js
It would be great if Svane could just read the breakpoints from the Tailwind config file. 

More infos: https://stackoverflow.com/questions/71633327/referencing-tailwindcss-config-from-javascript-in-sveltekit

A quick attempt to do so failed, so I just added a TODO comment in the code.

### PR DESCRIPTION
**Pull request by Shackless**
I refactored the code to be more readable and easier to understand. 

Goal: resolve #1 and #4 (and #6)

Before we can merge this, we have to find out why the client sometimes reads an old version of the `tailwind.config.js`. I added a demo custom config and if I `console.log` this outside of the client-only `onMount()` function, I always see the correct values. If I do this inside of `onMount()`, I get the default config without my changes. I'm pretty sure that at some point I saw an older custom config there - so maybe it's some kind of caching? Maybe caused by the changes to `vite.config`?

### CODE REVIEW

**Comment by jwatts777** [comment]
I spent a couple of hours playing around with it, but I can't make sense of why the tailwind config file won't update at all.  It looks to be properly implemented per the docs. 
Probably best to post the config on the vite github and see what tiny thing we're missing.

**Comment by Shackless** [comment]
@jwatts777 I think I found the culprit: We need to force-reload the `tailwind.config.js` using

```js
export default defineConfig({
	optimizeDeps: {
		include: ['tailwind-config'],
		force: true // force to refresh the config file on change in DEV mode
	},
	// ...
});
```

After changes to the config, you also need to restart the dev server. I added these infos the to README and demo page.

Could you double-check if it's working for you, too?

**Comment by jwatts777** [comment]
> @jwatts777 I think I found the culprit: We need to forcce-reload the `tailwind.config.js` using
> 
> ```js
> export default defineConfig({
> 	optimizeDeps: {
> 		include: ['tailwind-config'],
> 		force: true // force to refresh the config file on change in DEV mode
> 	},
> 	// ...
> });
> ```
> 
> After changes to the config, you also need to restart the dev server. I added these infos the to README and demo page.
> 
> Could you double-check if it's working for you, too?

Give me a sec and I will spin one up. That's a interesting vite config option. 
Wonder why it's not default. Will be making a note to add to all future and current projects.

**Comment by jwatts777** [comment]
Looks good to me, and functions as expected.

**Pull request merged**
